# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'tty-prompt'
gem 'tty-box'
gem 'colorize'
gem 'artii'
gem 'json'


# gem "rails"
